services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile 
    ports:
      - "8001:8001"
    env_file:
      - .env

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile 
    ports:
      - 8501:8501
    env_file:
      - .env
    environment:
      - BACKEND_URL=http://backend:8001 
    depends_on:
      - backend
    volumes:
      - ./public:/app/public
